### PR TITLE
Updating index to match current starter app

### PR DESCRIPTION
**Pull request by ryelo**
Recently, we changed the ESI structure. Your app may look broken when deployed or using the latest version of insights-chrome. This should fix up the issue!

Related: https://github.com/RedHatInsights/insights-frontend-starter-app/pull/55

### CODE REVIEW

**Comment by adamruzicka** [comment]
This indeed fixes the broken rendering issue, but it looks different. Can I safely assume the changes come from the patternfly update?

Before:
image

After:
image

**Comment by bastilian** [comment]
Updating `@red-hat-insights/insights-frontend-components` and `@patternfly/patternfly-next` pacakges to the latest doesn't appear to fix the issue.

**Comment by ryelo** [comment]
^ Updating the two packages above should solve your issues.

**Comment by adamruzicka** [comment]
~~Could you please update the versions in `package-lock.json` required to make this work properly as part of this pr?~~

Nevermind, being handled in https://github.com/RedHatInsights/notifications-frontend/pull/6

**Comment by bastilian** [comment]
@adamruzicka `@patternfly/react-core` needed an update as well. the squished header will not occur with #6 applied.

**Comment by bastilian** [comment]
Thank you @ryelo!

**Pull request merged**
