### PR TITLE
Rename

### PR DESCRIPTION
**Pull request by adamruzicka**
Opening as a draft since the changes need to be coordinated across projects to minimize downtime

### CODE REVIEW

**Comment by iphands** [comment]
@adamruzicka  its vital that we change https://github.com/RedHatInsights/notifications-frontend/blob/master/package.json#L125 too

**Comment by adamruzicka** [comment]
Done

**Comment by bastilian** [comment]
Thanks @adamruzicka!

**Comment by iphands** [comment]
@bastilian @adamruzicka can you also send this to stable?
I am trying to close out work on our side, and I'd like to see the hooks stable release

**Comment by adamruzicka** [comment]
It should be out there now

**Pull request merged**
