### PR TITLE
Show selected-all radio toggle for levels 

### PR DESCRIPTION
**Pull request by adamruzicka**
It is not that nice but plain checkboxes don't give us the expresiveness we need.

### CODE REVIEW

**Comment by adamruzicka** [comment]
Now based on https://github.com/RedHatInsights/notifications-frontend/pull/47 . I wrapped everything in lists so the spacing should look nicer now

image

**Comment by adamruzicka** [comment]
I had to undo some of the styling changes done to the radio toggle

With custom styling:
image

Without custom styling:
image

The title is still a tiny bit off

**Comment by adamruzicka** [comment]
Hopefully it should be all aligned
image

**Comment by bastilian** [comment]
It doesn't seem to save all levels, when previously only selected levels were checked.

**Comment by bastilian** [comment]
Thanks @adamruzicka! Works great now!

**Pull request merged**
