### PR TITLE
Update index to match mockups

### PR DESCRIPTION
**Pull request by bastilian**
* Update columns to 'Name', 'Type', 'Path', 'Status', 'Active'
* Add StatusIcon component
* Use HTTP as placholder for type

Screen Shot 2019-04-01 at 13 19 25

### CODE REVIEW

**Review by adamruzicka — CHANGES_REQUESTED** [review]
Looks great, but the headers (or contents?) in path and type should be swapped.

**Comment by bastilian** [comment]
Good catch! It's corrected:

Screen Shot 2019-04-01 at 13 51 30

**Comment by adamruzicka** [comment]
Needs a rebase

**Review by adamruzicka — APPROVED** [review]
Looks great :+1:

**Comment by adamruzicka** [comment]
Thanks @bastilian !

**Pull request merged**
